language: python
python:
  - "2.7"
install:
    - python bootstrap.py --buildout-version=2.5.3 --setuptools-version=33.1.1
    - bin/buildout
script:
    - bin/test -pvc
notifications:
    email: tseaver@palladion.com
